return {}
-- return {
--   {
--     "sidebar-nvim/sidebar.nvim",
--     config = function()
--       local sidebar = require("sidebar-nvim")
--       sidebar.setup({
--         side = "right",
--         open = false,
--         update_interval = 100,
--         disable_closing_prompt = true,
--       })
--     end,
--   },
-- }
